### ISSUE TITLE
OPT Models Fail to Pack During Quantization

### ISSUE THREAD

**Issue by official-elinas** [qwopqwop200/GPTQ-for-LLaMa#101]
# Issue Description

When running the `opt.py` conversion script with the following cli arguments: 

`python opt.py "OPT-30B-Shard" c4 --wbits 4 --save opt-30b-4bit.pt` 

## Errors

I get the following error once packing starts, everything else runs fine with the above commands:

```
Traceback (most recent call last):
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 503, in <module>
    opt_pack(model, quantizers, args.wbits, args.groupsize)
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 244, in opt_pack
    layers = {n: layers[n] for n in quantizers}
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 244, in <dictcomp>
    layers = {n: layers[n] for n in quantizers}
KeyError: 'model.layers.0.self_attn.k_proj'
```

It also does not work with `--true-sequential` and fails with the following error (assuming since the tensors are not in the correct order):
```
Ready.
0 self_attn.k_proj
Quantizing ...
time 10.59
error 19059.69921875
0 self_attn.v_proj
Quantizing ...
time 5.23
error 15892.580078125
0 self_attn.q_proj
Quantizing ...
time 5.30
error 21565.109375
Traceback (most recent call last):
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 473, in <module>
    quantizers = opt_sequential(model, dataloader, DEV)
  File "G:\llm-webui\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 92, in opt_sequential
    subset = {n: full[n] for n in names}
  File "G:\llm-webui\text-generation-webui\repositories\GPTQ-for-LLaMa\opt.py", line 92, in <dictcomp>
    subset = {n: full[n] for n in names}
KeyError: 'self_attn.o_proj'
```

I tried running `groupsize 128` as well, but my system kept crashing during quant, so I did not add that flag on subsequent attempts. 

At this point it would be nice to know how to just fix this without `true-sequential` or `groupsize`. 

Thanks.

**Comment by mityarko** [comment]
Same error with `groupsize 128`:
`python opt.py "C:\GPT\text-generation-webui\models\OPT-350M-Erebus" c4 --wbits 4 --groupsize 128 --save opt-350m-erebus-g128-4bit.pt`:
```
Traceback (most recent call last):
  File "C:\GPT\text-generation-webui\repositories\GPTQ-for-LLaMa-pytorch\opt.py", line 496, in <module>
    opt_pack(model, quantizers, args.wbits, args.groupsize)
  File "C:\GPT\text-generation-webui\repositories\GPTQ-for-LLaMa-pytorch\opt.py", line 244, in opt_pack
    layers = {n: layers[n] for n in quantizers}
  File "C:\GPT\text-generation-webui\repositories\GPTQ-for-LLaMa-pytorch\opt.py", line 244, in <dictcomp>
    layers = {n: layers[n] for n in quantizers}
KeyError: 'model.layers.0.self_attn.k_proj'
```

**Comment by GenTxt** [comment]
Confirming same errors above with opt30b. 

Pre-cuda pytorch version worked.

**Comment by qwopqwop200** [comment]
fix it
