### ISSUE TITLE
hipconfig Error while I'm using Nvidia RTX 4090 in Ubuntu 20.04

### ISSUE THREAD

**Issue by charleschen2006** [qwopqwop200/GPTQ-for-LLaMa#112]
when I install cuda there is an error about hipconfig in setup_cuda.py. I do not have any AMD GPU cards it's ridiclus!
=============================================================================================
$ python setup_cuda.py install
Traceback (most recent call last):
  File "/home/charles/JQZX/text-generation-webui/repositories/GPTQ-for-LLaMa/setup_cuda.py", line 2, in <module>
    from torch.utils import cpp_extension
  File "/home/charles/miniconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/home/charles/miniconda3/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/home/charles/miniconda3/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/home/charles/miniconda3/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/charles/miniconda3/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/charles/miniconda3/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/charles/miniconda3/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'

**Comment by qwopqwop200** [comment]
currently using triton, so I don't think this problem will occur.
