### ISSUE TITLE
TypeError: '<' not supported between instances of 'float' and 'tuple'

### ISSUE THREAD

**Issue by jgsch** [qwopqwop200/GPTQ-for-LLaMa#118]
I've created the conda env like in the README:
```
conda create --name gptq python=3.9 -y 
conda activate gptq 
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
pip install -r requirements.txt
```
Launch the quantization (with the already converted weights from huggingface, `decapoda-research/llama-7b-hf`) and start the benchmark:
```
CUDA_VISIBLE_DEVICES=0 python llama.py decapoda-research/llama-7b-hf c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save_safetensors llama7b-4bit-128g.safetensors 
CUDA_VISIBLE_DEVICES=0 python llama.py decapoda-research/llama-7b-hf c4 --wbits 4 --groupsize 128 --load llama7b-4bit-128g.safetensors --benchmark 2048 --check
```
But an error happens during the benchmark:
```
[...]
Benchmarking ...
Traceback (most recent call last):
  File "/home/jgsch/GPTQ-for-LLaMa/llama.py", line 519, in <module>
    benchmark(model, input_ids, check=args.check)
  File "/home/jgsch/GPTQ-for-LLaMa/llama.py", line 377, in benchmark
    out = model(
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jgsch/experiments/apps/chatbot/gptq/quant.py", line 759, in forward
    out = QuantLinearFunction.apply(
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 106, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/jgsch/GPTQ-for-LLaMa/quant.py", line 593, in forward
    matmul_248_kernel[grid](
  File "/home/jgsch/.miniconda3/envs/gptq/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 81, in run
    self.cache[key] = builtins.min(timings, key=timings.get)
TypeError: '<' not supported between instances of 'float' and 'tuple'
```
Any idea?

**Comment by qwopqwop200** [comment]
The model was converted to old Transformers. Convert the model again. Convert the model to new.

**Comment by jgsch** [comment]
its working, thanks!
