### ISSUE TITLE
'position_ids' Key Error, How to fix it? 

### ISSUE THREAD

**Issue by taeseokyi** [qwopqwop200/GPTQ-for-LLaMa#120]
Hello.

'position_ids' key error below occurs. I don't know what to do. If possible, please advise.

Thank you

(gptq) myserver:~/work/GPTQ-for-LLaMa$ CUDA_VISIBLE_DEVICES=0 python llama.py ../llama-7b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save llama-7b-4bit-128g.pt
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:21<00:00,  7.26s/it]
Found cached dataset json (/home/taeseok/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Found cached dataset json (/home/taeseok/.cache/huggingface/datasets/allenai___json/allenai--c4-efc3d4f4606f44bd/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Token indices sequence length is longer than the specified maximum sequence length for this model (3908 > 2048). Running this sequence through the model will result in indexing errors
Starting ...
Traceback (most recent call last):
  File "/home/taeseok/work/GPTQ-for-LLaMa/llama.py", line 452, in <module>
    quantizers = llama_sequential(model, dataloader, DEV)
  File "/home/taeseok/anaconda3/envs/gptq/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/taeseok/work/GPTQ-for-LLaMa/llama.py", line 54, in llama_sequential
    model(batch[0].to(dev))
  File "/home/taeseok/anaconda3/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/taeseok/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/taeseok/anaconda3/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/taeseok/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/home/taeseok/anaconda3/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/taeseok/work/GPTQ-for-LLaMa/llama.py", line 49, in forward
    cache['position_ids'] = kwargs['position_ids']
KeyError: 'position_ids'

**Comment by qwopqwop200** [comment]
```
pip uninstall transformers 
pip install git+https://github.com/huggingface/transformers
```

**Comment by taeseokyi** [comment]
It works. thank you.
