### ISSUE TITLE
TypeError: not a string when exec llama.py

### ISSUE THREAD

**Issue by little51** [qwopqwop200/GPTQ-for-LLaMa#125]
```
conda install -c conda-forge cudatoolkit-dev
mkdir repositories
cd repositories
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa
cd GPTQ-for-LLaMa
git reset --hard 468c47c01b4fe370616747b6d69a2d3f48bab5e4
python setup_cuda.py install
```
download model from decapoda-research/llama-7b-hf into ~/llama-7b-hf
when exce :
CUDA_VISIBLE_DEVICES=0 python llama.py ~/llama-7b-hf c4 --wbits 4 --groupsize 128 --save llama7b-4bit.pt
raise exception:
```
Traceback (most recent call last):
  File "/home/user01/GPTQ-for-LLaMa/llama.py", line 404, in <module>
    dataloader, testloader = get_loaders(
  File "/home/user01/GPTQ-for-LLaMa/datautils.py", line 111, in get_loaders
    return get_c4(nsamples, seed, seqlen, model)
  File "/home/user01/GPTQ-for-LLaMa/datautils.py", line 64, in get_c4
    tokenizer = AutoTokenizer.from_pretrained(model, use_fast=False)
  File "/home/user01/conda/envs/gptq/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 694, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/user01/conda/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/user01/conda/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/user01/conda/envs/gptq/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/user01/conda/envs/gptq/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/user01/conda/envs/gptq/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
```

**Comment by qwopqwop200** [comment]
The model was converted to old Transformers. Convert the model again

**Comment by little51** [comment]
Thank you for your quick reply. how to Convert the model again ?

**Comment by qwopqwop200** [comment]
> Thank you for your quick reply. how to Convert the model again ?

huggyllama/llama-7b use it

**Comment by little51** [comment]
It's working! Thank you very much!

**Comment by lunaryan** [comment]
If you also see the warning: "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'PreTrainedTokenizerFast'.
The class this function is called from is 'LlamaTokenizer'.
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will
not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565 ", make sure to set tokenizer type to be None.
