### ISSUE TITLE
ValueError: Couldn't instantiate the backend tokenizer from one of

### ISSUE THREAD

**Issue by JinEui-Kim** [qwopqwop200/GPTQ-for-LLaMa#140]
i've clone https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g repository and run 'git lfs clone'

and i tried to run with llama_inference.py like below
```
CUDA_VISIBLE_DEVICES=1 python llama_inference.py /home/td/jini/GPTQ-for-LLaMa/model/gpt4-x-alpaca-13b-native-4bit-128g/ \
	--wbits 4 \
	--groupsize 128 \
	--load /home/td/jini/GPTQ-for-LLaMa/model/gpt4-x-alpaca-13b-native-4bit-128g/gpt-x-alpaca-13b-native-4bit-128g.pt \
	--text "this is llama"
```

i tried both of triton branch and cuda branch.
but i got same error below.
```
Loading model ...
Done.
Traceback (most recent call last):
  File "/home/td/jini/GPTQ-for-LLaMa/llama_inference.py", line 125, in <module>
    tokenizer = AutoTokenizer.from_pretrained(args.model)
  File "/home/td/anaconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 700, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/td/anaconda3/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/td/anaconda3/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/td/anaconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 74, in __init__
    super().__init__(
  File "/home/td/anaconda3/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 120, in __init__
    raise ValueError(
ValueError: Couldn't instantiate the backend tokenizer from one of: 
(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
```

i tried to find the solution.
They said "pip install sentencepiece" but i already install sentencepiece.

here is my environments
Ubuntu 20.04
CUDA 11.8
python 3.9.16
AMD Ryzen 9 5900X 12-Core Processor
NVIDIA RTX A6000

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.17.1                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
blas                      1.0                         mkl  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py39h06a4308_0  
cffi                      1.15.1           py39h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cmake                     3.26.1                   pypi_0    pypi
cryptography              39.0.1           py39h9ce1e76_0  
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
datasets                  2.10.1                   pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.9.0            py39h06a4308_0  
flit-core                 3.8.0            py39h06a4308_0  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.3.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py39heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
huggingface-hub           0.13.3                   pypi_0    pypi
idna                      3.4              py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.1.2            py39h06a4308_0  
jpeg                      9e                   h5eee18b_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.0.25                      0    nvidia
libcurand                 10.3.2.56                     0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lit                       16.0.0                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1            py39h7f8727e_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.2.1            py39h06a4308_0  
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.8.4            py39h06a4308_1  
numpy                     1.23.5           py39h14f4228_0  
numpy-base                1.23.5           py39h31eccc5_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
pillow                    9.4.0            py39h6a678d5_0  
pip                       23.0.1           py39h06a4308_0  
protobuf                  3.20.2                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0           py39h06a4308_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   2.0.0           py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
quant-cuda                0.0.0                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.1           py39h06a4308_1  
responses                 0.18.0                   pypi_0    pypi
safetensors               0.3.0                    pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                65.6.3           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.1               h5eee18b_0  
sympy                     1.11.1           py39h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
torchaudio                2.0.0                py39_cu117    pytorch
torchtriton               2.0.0                      py39    pytorch
torchvision               0.15.0               py39_cu117    pytorch
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.28.0.dev0              pypi_0    pypi
typing_extensions         4.4.0            py39h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15          py39h06a4308_0  
wheel                     0.38.4           py39h06a4308_0  
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.10               h5eee18b_1  
yarl                      1.8.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.4                hc292b87_0  
```

i don't know what is the reason of this error.
could you give the hint for me?

**Comment by qwopqwop200** [comment]
`tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=False)`
I think this will solve your problem.

**Comment by JinEui-Kim** [comment]
> `tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=False)` I think this will solve your problem.

Thanks. it works
