### ISSUE TITLE
Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by C0rn3j** [qwopqwop200/GPTQ-for-LLaMa#18]
I am not sure how to deal with this.

Python 3.10.9 on Arch Linux.

```python
[0] # CUDA_VISIBLE_DEVICES=0 python llama.py decapoda-research/llama-7b-hf c4 --wbits 4 --save llama7b-4bit.pt

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:09<00:00,  3.60it/s]
Downloading readme: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.38k/2.38k [00:00<00:00, 3.79MB/s]
Downloading and preparing dataset json/allenai--c4 to /root/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 319M/319M [01:13<00:00, 4.36MB/s]
Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:14<00:00, 74.30s/it]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
Downloading and preparing dataset json/allenai--c4 to /root/.cache/huggingface/datasets/allenai___json/allenai--c4-efc3d4f4606f44bd/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40.5M/40.5M [00:06<00:00, 6.15MB/s]
Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.63s/it]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.17it/s]
Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/allenai___json/allenai--c4-efc3d4f4606f44bd/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 141/141 [00:00<00:00, 175kB/s]
Traceback (most recent call last):
  File "/root/llama/GPTQ-for-LLaMa/llama.py", line 393, in <module>
    dataloader, testloader = get_loaders(
  File "/root/llama/GPTQ-for-LLaMa/datautils.py", line 111, in get_loaders
    return get_c4(nsamples, seed, seqlen, model)
  File "/root/llama/GPTQ-for-LLaMa/datautils.py", line 64, in get_c4
    tokenizer = AutoTokenizer.from_pretrained(model, use_fast=False)
  File "/root/llama/venv/lib/python3.10/site-packages/transformers-4.27.0.dev0-py3.10.egg/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
(venv) 
```

```python
[0] # pip list
Package                  Version            Editable project location
------------------------ ------------------ ---------------------------------------------
aiohttp                  3.8.4
aiosignal                1.3.1
astunparse               1.6.3
async-timeout            4.0.2
attrs                    22.2.0
certifi                  2022.12.7
charset-normalizer       3.1.0
datasets                 2.10.1
dill                     0.3.6
exceptiongroup           1.1.0
expecttest               0.1.4
filelock                 3.9.0
frozenlist               1.3.3
fsspec                   2023.3.0
huggingface-hub          0.13.1
hypothesis               6.68.2
idna                     3.4
Jinja2                   3.1.2
MarkupSafe               2.1.2
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
networkx                 3.0
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
pandas                   1.5.3
pip                      22.3.1
psutil                   5.9.4
pyarrow                  11.0.0
python-dateutil          2.8.2
pytz                     2022.7.1
PyYAML                   6.0
quant-cuda               0.0.0
regex                    2022.10.31
requests                 2.28.2
responses                0.18.0
setuptools               65.5.0
six                      1.16.0
sortedcontainers         2.4.0
sympy                    1.11.1
tokenizers               0.13.2
torch                    2.1.0a0+gitc7bd9b9 /root/llama/venv/lib/python3.10/site-packages
tqdm                     4.65.0
transformers             4.27.0.dev0
types-dataclasses        0.6.6
typing_extensions        4.5.0
urllib3                  1.26.14
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.8.2
```

**Comment by qwopqwop200** [comment]
It is possible that the checkpoint is out of date.
Try converting again.

**Comment by C0rn3j** [comment]
Do you mean by running `python setup_cuda.py install` again? 

Because that's what downloaded the checkpoints in the first place

**Comment by brandonrobertz** [comment]
Torch version is too new. Try 1.X

**Comment by C0rn3j** [comment]
I am on CUDA 12.1, which is not supported by torch 1.x.

**Comment by brandonrobertz** [comment]
I had to downgrade my CUDA stack down to 11.7 and use torch 1.13. Best of luck!

**Comment by DanielWe2** [comment]
I had the same issue. In my case the pip package sentencepiece was missing preventing some imports in the LLaMa modules of transformers.

**Comment by brandonrobertz** [comment]
> I had the same issue. In my case the pip package sentencepiece was missing preventing some imports in the LLaMa modules of transformers.

Interesting. sentencepiece is a dependency of transformers, so a proper and successful install of transformers should result in sentencepiece being installed as well.

**Comment by C0rn3j** [comment]
@brandonrobertz That is not correct - https://github.com/pytorch/pytorch/blob/master/requirements.txt

@DanielWe2 Yep, that was it for me too, thanks for finding it out!

**Comment by brandonrobertz** [comment]
> @brandonrobertz That is not correct - https://github.com/pytorch/pytorch/blob/master/requirements.txt

That's the wrong library. It's a dep of transformers, not torch:

https://github.com/huggingface/transformers/blob/main/setup.py#L162

Since you need to use the fork specified in the README (`-e git+https://github.com/zphang/transformers@660dd6e2bbc9255aacd0e60084cf15df1b6ae00d#egg=transformers`), this is a common failure mode for people.

**Comment by Azeirah** [comment]
I'm still not sure how to fix this. I'm getting this import exception as well.

```sh
(gptq)$ pip list
Package                  Version
------------------------ -----------
accelerate               0.17.1
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   4.2.2
anyio                    3.6.2
async-timeout            4.0.2
attrs                    22.2.0
bitsandbytes             0.37.1
brotlipy                 0.7.0
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       2.0.4
click                    8.1.3
contourpy                1.0.7
cryptography             39.0.1
cycler                   0.11.0
entrypoints              0.4
fastapi                  0.94.1
ffmpy                    0.3.0
filelock                 3.9.0
flexgen                  0.1.7
flit_core                3.6.0
fonttools                4.39.2
frozenlist               1.3.3
fsspec                   2023.3.0
gmpy2                    2.1.2
gradio                   3.18.0
h11                      0.14.0
httpcore                 0.16.3
httpx                    0.23.3
huggingface-hub          0.13.2
idna                     3.4
importlib-metadata       6.0.0
importlib-resources      5.12.0
Jinja2                   3.1.2
jsonschema               4.17.3
kiwisolver               1.4.4
linkify-it-py            2.0.0
Markdown                 3.4.1
markdown-it-py           2.2.0
MarkupSafe               2.1.1
matplotlib               3.7.1
mdit-py-plugins          0.3.5
mdurl                    0.1.2
mkl-fft                  1.3.1
mkl-random               1.2.2
mkl-service              2.4.0
mpmath                   1.2.1
multidict                6.0.4
networkx                 2.8.4
numpy                    1.23.5
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
orjson                   3.8.7
packaging                23.0
pandas                   1.5.3
peft                     0.2.0
Pillow                   9.4.0
pip                      23.0.1
psutil                   5.9.4
PuLP                     2.7.0
pycparser                2.21
pycryptodome             3.17
pydantic                 1.10.6
pydub                    0.25.1
pyOpenSSL                23.0.0
pyparsing                3.0.9
pyrsistent               0.19.3
PySocks                  1.7.1
python-dateutil          2.8.2
python-multipart         0.0.6
pytz                     2022.7.1
PyYAML                   6.0
quant-cuda               0.0.0
regex                    2022.10.31
requests                 2.28.1
rfc3986                  1.5.0
rwkv                     0.4.2
safetensors              0.3.0
sentencepiece            0.1.94
setuptools               65.6.3
six                      1.16.0
sniffio                  1.3.0
starlette                0.26.1
sympy                    1.11.1
tokenizers               0.13.2
toolz                    0.12.0
torch                    1.13.1
torchaudio               2.0.0
torchvision              0.15.0
tqdm                     4.65.0
transformers             4.28.0.dev0
triton                   2.0.0
typing_extensions        4.4.0
uc-micro-py              1.0.1
urllib3                  1.26.14
uvicorn                  0.21.1
websockets               10.4
wheel                    0.38.4
yarl                     1.8.2
zipp                     3.15.0
```

```sh
(gptq) /LLaMA/text-generation-webui$ tree models
├── llama-7b
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   └── params.json
├── llama-7b-4bit.pt
├── llama-7b-hf
│   ├── config.json
│   ├── generation_config.json
│   ├── pytorch_model.bin.index.json
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── tokenizer.model
└── place-your-models-here.txt
```

```sh
(gptq) $ python server.py --gptq-bits 4 --model llama-7b-hf

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/lb/miniconda3/envs/gptq did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /usr/lib/x86_64-linux-gnu:/usr/lib did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/2018,unix/lb-desktop'), PosixPath('local/lb-desktop')}
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/ubuntu.mandatory.path')}
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/446d1daa_a336_4437_b62c_13553df3323e')}
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/ubuntu.default.path')}
  warn(msg)
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//debuginfod.ubuntu.com '), PosixPath('https')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
Loading llama-7b-hf...
CUDA extension not installed.
Loading model ...
Done.
Traceback (most recent call last):
  File "/home/lb/Downloads/LLaMA/text-generation-webui/server.py", line 236, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/lb/Downloads/LLaMA/text-generation-webui/modules/models.py", line 158, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"models/{shared.model_name}/"))
  File "/home/lb/miniconda3/envs/gptq/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported
```

> I had to downgrade my CUDA stack down to 11.7 and use torch 1.13. Best of luck!

I am using CUDA version 11.7 as well, with torch 1.13.1

> > @brandonrobertz That is not correct - https://github.com/pytorch/pytorch/blob/master/requirements.txt
> 
> That's the wrong library. It's a dep of transformers, not torch:
> 
> https://github.com/huggingface/transformers/blob/main/setup.py#L162
> 
> Since you need to use the fork specified in the README (`-e git+https://github.com/zphang/transformers@660dd6e2bbc9255aacd0e60084cf15df1b6ae00d#egg=transformers`), this is a common failure mode for people.

My sentencepiece is installed as version 0.1.94. Which satisfies the constraint in the link.

**Comment by BEpresent** [comment]
For anyone experiencing this problem, it could be related to the entry inside the `tokenizer_config.json` as they changed this recently: (`LlamaTokenizer` not `LLaMaTokenizer` ). 

```
"tokenizer_class": "LlamaTokenizer",
```

Changing this solved it for me.

**Comment by clxyder** [comment]
> For anyone experiencing this problem, it could be related to the entry inside the `tokenizer_config.json` as they changed this recently: (`LlamaTokenizer` not `LLaMaTokenizer` ).
> 
> ```
> "tokenizer_class": "LlamaTokenizer",
> ```
> 
> Changing this solved it for me.

I can confirm this is the correct solution to the problem.

https://github.com/huggingface/transformers/issues/22222#issuecomment-1477171703
