### ISSUE TITLE
NameError: name 'transformers' is not defined

### ISSUE THREAD

**Issue by catalpaaa** [qwopqwop200/GPTQ-for-LLaMa#198]
```
Traceback (most recent call last):
  File "/home/catalpa/nas/program/text-generation-webui/server.py", line 917, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/catalpa/nas/program/text-generation-webui/modules/models.py", line 127, in load_model
    model = load_quantized(model_name)
  File "/home/catalpa/nas/program/text-generation-webui/modules/GPTQ_loader.py", line 170, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, shared.args.pre_layer)
  File "/home/catalpa/nas/program/text-generation-webui/repositories/GPTQ-for-LLaMa/llama_inference_offload.py", line 195, in load_quant
    transformers.models.llama.modeling_llama.LlamaModel = Offload_LlamaModel
NameError: name 'transformers' is not defined
```

**Comment by qwopqwop200** [comment]
Does it work properly now?

**Comment by tpoisonooo** [comment]
@catalpaaa  just add `import transformers`.

**Comment by Cebtenzzre** [comment]
This issue also affects llama.py, llama_inference.py, llama_inference_dmapauto.py, and llama_inference_offload.py on the cuda branch.
