### ISSUE TITLE
NameError: name 'quant_cuda' is not defined

### ISSUE THREAD

**Issue by CyberTimon** [qwopqwop200/GPTQ-for-LLaMa#21]
I loaded successfully the 7b llama model in 4bit but when I try to generate some text this happens:

Starting the web UI...
Loading the extension "gallery"... Ok.
Loading llama-7b...
CUDA extension not installed.
Loading model ...
Done.
Loaded the model in 4.07 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 849, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\gradio\utils.py", line 453, in async_iteration
    return next(iterator)
  File "C:\Users\zblac\Downloads\oobabooga\text-generation-webui\modules\chat.py", line 126, in chatbot_wrapper
    for reply in generate_reply(f"{prompt}{' ' if len(reply) > 0 else ''}{reply}", max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, eos_token=eos_token, stopping_string=f"\n{name1}:"):
  File "C:\Users\zblac\Downloads\oobabooga\text-generation-webui\modules\text_generation.py", line 170, in generate_reply
    output = eval(f"shared.model.generate({', '.join(generate_params)}){cuda}")[0]
  File "<string>", line 1, in <module>
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1452, in generate
    return self.sample(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2468, in sample
    outputs = self(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 772, in forward
    outputs = self.model(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 621, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 318, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 218, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Users\zblac\Downloads\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\zblac\Downloads\oobabooga\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 198, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.zeros)
NameError: name 'quant_cuda' is not defined

**Comment by CyberTimon** [comment]
Fixed. I had to copy the quant_cuda files from the normal site packages to the env where the text generation webui was

**Comment by another1s** [comment]
@CyberTimon Hello, I encountered the same problem. Could you please enlighten me? I have already copied that quant_cude.cpp file to my working directory but it does not work.....
