### ISSUE TITLE
How can I get the gradient when using 4bits model?

### ISSUE THREAD

**Issue by Joanna-0421** [qwopqwop200/GPTQ-for-LLaMa#211]
When I use the 4bits llama model and run loss.backward(), the following error occurs:
Traceback (most recent call last):
  File "/home/zzy/anaconda3/envs/gptq/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zzy/anaconda3/envs/gptq/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zzy/.vscode-server/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/zzy/.vscode-server/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/zzy/.vscode-server/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/zzy/.vscode-server/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/zzy/.vscode-server/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/zzy/.vscode-server/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/zzy/workplace/ICA/llama/GPTQ-for-LLaMa/llama_ICA.py", line 300, in <module>
    loss.backward(retain_graph=True)
  File "/home/zzy/anaconda3/envs/gptq/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/zzy/anaconda3/envs/gptq/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected is_sm80 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

I wondering if I could get the gradient when using the 4bits model.

**Comment by j0hngou** [comment]
That depends on what you're trying to do. Your stack trace and the error are not very informative but I am guessing you are trying to train the model itself. If you look at the [QuantLinear](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/quant/quant_linear.py#L299) autograd function, you can only get the gradient with respect to the input (\nabla_X Y), not the weights, scales or zeros. Even if you implement these, doing the update itself is nontrivial (although there are ways to train quantized networks, i.e., QAT, it doesn't readily work for GPTQ's quantization method (OBC)). It's definitely doable though.

What you CAN do with the \nabla_X Y grad is freeze the quantized weights, introduce new parameters, and train those instead (there are lots of methods here, see adapters, LoRA, prefix-tuning, etc). At some points, you will need the \nabla_X Y grad due to the chain rule.
