### ISSUE TITLE
4bits on 65B

### ISSUE THREAD

**Issue by jear** [qwopqwop200/GPTQ-for-LLaMa#213]
Interesting bug 👍 
``` 
CUDA_VISIBLE_DEVICES=0 python llama.py ${MODEL_DIR} c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save llama65b-4bit-128g.pt --nsamples 1
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 14/14 [04:07<00:00, 17.67s/it]
Found cached dataset json (/home/ubuntu/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Found cached dataset json (/home/ubuntu/.cache/huggingface/datasets/allenai___json/allenai--c4-efc3d4f4606f44bd/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Starting ...
Ready.
Quantizing layer 1/80..
+------------------+--------------+------------+-----------+-------+
|       name       | weight_error | fp_inp_SNR | q_inp_SNR | time  |
+==================+==============+============+===========+=======+
| self_attn.k_proj | 17.887       | -          | -         | 7.458 |
| self_attn.v_proj | 2.429        | -          | -         | 6.350 |
| self_attn.q_proj | 15.419       | -          | -         | 6.276 |
| self_attn.o_proj | 0.481        | -          | -         | 6.549 |
| mlp.up_proj      | 7.348        | -          | -         | 7.193 |
| mlp.gate_proj    | 8.498        | -          | -         | 6.851 |
| mlp.down_proj    | 0.943        | -          | -         | 26.461 |
+------------------+--------------+------------+-----------+-------+


Quantizing layer 2/80..
+------------------+--------------+------------+-----------+-------+
|       name       | weight_error | fp_inp_SNR | q_inp_SNR | time  |
+==================+==============+============+===========+=======+
| self_attn.k_proj | 119.764      | -          | -         | 6.687 |
| self_attn.v_proj | 19.730       | -          | -         | 6.454 |
| self_attn.q_proj | 118.585      | -          | -         | 6.475 |
| self_attn.o_proj | 1.342        | -          | -         | 6.652 |
| mlp.up_proj      | 63.378       | -          | -         | 7.255 |
| mlp.gate_proj    | 74.828       | -          | -         | 6.970 |
| mlp.down_proj    | 3.068        | -          | -         | 27.540 |
+------------------+--------------+------------+-----------+-------+


Quantizing layer 3/80..
+------------------+--------------+------------+-----------+-------+
|       name       | weight_error | fp_inp_SNR | q_inp_SNR | time  |
+==================+==============+============+===========+=======+
| self_attn.k_proj | 149.281      | -          | -         | 6.852 |
| self_attn.v_proj | 34.353       | -          | -         | 6.507 |
| self_attn.q_proj | 141.124      | -          | -         | 6.518 |
| self_attn.o_proj | 3.667        | -          | -         | 6.736 |
| mlp.up_proj      | 190.208      | -          | -         | 7.349 |
| mlp.gate_proj    | 226.558      | -          | -         | 7.024 |
Traceback (most recent call last):
  File "/home/ubuntu/workspace/github/GPTQ-for-LLaMa/llama.py", line 479, in <module>
    quantizers = llama_sequential(model, dataloader, DEV)
  File "/home/ubuntu/miniconda3/envs/gptq/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/workspace/github/GPTQ-for-LLaMa/llama.py", line 114, in llama_sequential
    scale, zero, g_idx, error = gptq[name].fasterquant(percdamp=args.percdamp, groupsize=args.groupsize, actorder=args.act_order, name=name)
  File "/home/ubuntu/workspace/github/GPTQ-for-LLaMa/gptq.py", line 161, in fasterquant
    H = torch.linalg.cholesky(H)
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 18 is not positive-definite).

```

**Comment by qwopqwop200** [comment]
This isn't a bug. This is a phenomenon caused by numerical instability. Because of this, you need to use n samples that are large enough.
