### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by ahnHeejune** [qwopqwop200/GPTQ-for-LLaMa#249]
(vicuna) ahnlab@ahnlab-desktop:~/GPT/StarCoder/GPTQ-for-SantaCoder$ python -m santacoder_inference bigcode/starcoderbase --wbits 4 --groupsize 128 --load starcoderbase-GPTQ-4bit-128g/model.pt
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:12<00:00, 10.29s/it]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ahnlab/GPT/StarCoder/GPTQ-for-SantaCoder/santacoder_inference.py", line 90, in <module>
    main()
  File "/home/ahnlab/GPT/StarCoder/GPTQ-for-SantaCoder/santacoder_inference.py", line 80, in main
    model = get_santacoder(args.model, args.load, args.wbits, args.groupsize)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahnlab/GPT/StarCoder/GPTQ-for-SantaCoder/santacoder_inference.py", line 40, in get_santacoder
    model.load_state_dict(torch.load(checkpoint))
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahnlab/miniconda3/envs/vicuna/lib/python3.11/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahnlab/miniconda3/envs/vicuna/lib/python3.11/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by YangYang-DLUT** [comment]
Is it solved? I met the same problem.
