### ISSUE TITLE
Benchmark fails when using 4bit file

### ISSUE THREAD

**Issue by ItsLogic** [qwopqwop200/GPTQ-for-LLaMa#3]
Trying to test these models in 4bit but having an issue running the benchmark on the compressed file.

The command
`CUDA_VISIBLE_DEVICES=0 python llama.py decapoda-research/llama-7b-hf c4 --load llama7b-4bit.pt --benchmark 2048 --check`
fails on my machine with the log
```
Benchmarking ...
Traceback (most recent call last):
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/llama.py", line 410, in <module>
    benchmark(model, input_ids, check=args.check)
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/llama.py", line 309, in benchmark
    out = model(
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 857, in forward
    outputs = self.model.decoder(
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 629, in forward
    layer_outputs = decoder_layer(
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1208, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 310, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/DataButButter/AI/Text/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 199, in forward
    attn_weights = torch.bmm(query_states, key_states.transpose(1, 2)) / math.sqrt(self.head_dim)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

For extra information the kernel test completes successfully
```
Benchmarking LLaMa-33B FC2 matvec ...
FP16: 0.0007241859436035157
4bit: 0.00010311341285705566
Verifiying kernel correctness ...
Simu: tensor([-0.5063, -0.5161,  0.7185,  ..., -0.0747, -0.4014,  0.3023],
       device='cuda:0')
Kern: tensor([-0.5063, -0.5161,  0.7185,  ..., -0.0747, -0.4014,  0.3023],
       device='cuda:0')
```

The benchmark also completes successfully when just using the normal HF model  without 4bit conversion.

**Comment by qwopqwop200** [comment]
I cannot reproduce this problem.
It's probably a problem caused by your cuda version being low.

**Comment by ahsima1** [comment]
It also fails for me, but with a different error.
`CUDA_VISIBLE_DEVICES=0 CUDA_LAUNCH_BLOCKING=1 python llama.py decapoda-research/llama-7b-hf c4 --load llama7b-4bit.pt --benchmark 2048`

```
Benchmarking ...
Traceback (most recent call last):
  File "/home/x/llama/GPTQ-for-LLaMa/llama.py", line 407, in <module>
    benchmark(model, input_ids, check=args.check)
  File "/home/x/llama/GPTQ-for-LLaMa/llama.py", line 306, in benchmark
    out = model(
  File "/home/x/.conda/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 852, in forward
    outputs = self.model.decoder(
  File "/home/x/.conda/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 624, in forward
    layer_outputs = decoder_layer(
  File "/home/x/.conda/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 317, in forward
    hidden_states = self.feed_forward(hidden_states)
  File "/home/x/.conda/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 103, in forward
    return self.w2(self.act_fn(self.w1(x)) * self.w3(x))
  File "/home/x/.conda/envs/gptq/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x/llama/GPTQ-for-LLaMa/quant.py", line 165, in forward
    y = self.bias.clone()
RuntimeError: CUDA error: an illegal memory access was encountered
```
I'm using cuda version 11.7, installed from anaconda

**Comment by qwopqwop200** [comment]
I have not been able to reproduce this issue either.
Running using cuda 11.3 and torch 1.12.1+cu11.3 might help.

**Comment by Starlento** [comment]
Just a reference.
4090, WSL2, python 3.10, gcc and g++ 9.5, cuda 11.3, pytorch: `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117`.
Seems ok.
``` shell
Median: 0.015739798545837402
PPL: 6.336050987243652
max memory(MiB): 4740.1552734375
```

**Comment by qwopqwop200** [comment]
hmm... i don't know

**Comment by ahsima1** [comment]
Seems like there were breaking changes to the Transformers library branch for LLaMA support recently [https://github.com/huggingface/transformers/pull/21955#issuecomment-1459073934](https://github.com/huggingface/transformers/pull/21955#issuecomment-1459073934)

Once I updated the library and converted the weights using the newest version, I was able to run the benchmark.
```
Median: 0.03748023509979248
PPL: 6.315393447875977
max memory(MiB): 4676.1708984375
```

**Comment by ItsLogic** [comment]
Latest commits for transformers and this repo seem to work for me too. Not sure what the previous issue was but its gone now so I can get testing
```
Median: 0.01520681381225586
PPL: 6.328521251678467
max memory(MiB): 4676.1708984375
```
