### ISSUE TITLE
PosixPath object has no attribute endswith Win11 WSL2

### ISSUE THREAD

**Issue by rossbishop** [qwopqwop200/GPTQ-for-LLaMa#31]
```
$ python server.py --load-in-4bit --model llama-13b-hf
Loading llama-13b-hf...
Loading model ...
Traceback (most recent call last):
  File "/mnt/e/Projects/text-generation-webui/server.py", line 191, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/e/Projects/text-generation-webui/modules/models.py", line 119, in load_model
    model = load_quant(path_to_model, Path(f"models/{pt_model}"), 4)
  File "/mnt/e/Projects/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 241, in load_quant
    if checkpoint.endswith('.safetensors'):
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

Getting this issue when trying to run on Win11 under WSL2 with text generation WebUI. Behaviour is different prior to 68cfaf9dbeb1552a64c726660c9247fef14b1838, though still broken.

Output of `conda list`:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
blas                      1.0                         mkl
brotlipy                  0.7.0           py310h7f8727e_1002
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h7f8727e_0
ca-certificates           2023.01.10           h06a4308_0
certifi                   2022.12.7       py310h06a4308_0
cffi                      1.15.1          py310h5eee18b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
cryptography              39.0.1          py310h9ce1e76_0
curl                      7.88.1               h5eee18b_0
datasets                  2.10.1                   pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0
ffmpeg                    4.3                  hf484d3e_0    pytorch
flit-core                 3.6.0              pyhd3eb1b0_0
freetype                  2.12.1               h4a9f257_0
gdbm                      1.18                 hd4cb3f1_4
gettext                   0.21.0               hf68c758_0
giflib                    5.2.1                h5eee18b_3
git                       2.34.1          pl5262hc120c5b_0
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
icu                       58.2                 he6710b0_3
idna                      3.4             py310h06a4308_0
intel-openmp              2021.4.0          h06a4308_3561
jpeg                      9e                   h5eee18b_1
krb5                      1.19.4               h568e23c_0
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libcurl                   7.88.1               h91b91d3_0
libdeflate                1.17                 h5eee18b_0
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h7f8727e_1
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.2                h7f8727e_0
libnghttp2                1.46.0               hce63b2e_0
libpng                    1.6.39               h5eee18b_0
libssh2                   1.10.0               h8f2d780_0
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.16.0               h27cfd23_0
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libuuid                   1.41.5               h5eee18b_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
libxml2                   2.9.14               h74e7548_0
lz4-c                     1.9.4                h6a678d5_0
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0           py310h7f8727e_0
mkl_fft                   1.3.1           py310hd6ae3a3_0
mkl_random                1.2.2           py310h00e6091_0
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
numpy                     1.23.5          py310hd5efca6_0
numpy-base                1.23.5          py310h8e6c178_0
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1t               h7f8727e_0
pcre2                     10.37                he7ceb23_1
perl                      5.34.0               h5eee18b_2
pillow                    9.4.0           py310h6a678d5_0
pip                       23.0.1          py310h06a4308_0
pyarrow                   11.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pydub                     0.25.1                   pypi_0    pypi
pyopenssl                 23.0.0          py310h06a4308_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0
python                    3.10.9               h7a1cb2a_2
pytorch                   1.13.1             py3.10_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2022.7.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
quant-cuda                0.0.0                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
requests                  2.28.1          py310h06a4308_0
responses                 0.18.0                   pypi_0    pypi
rfc3986                   2.0.0                    pypi_0    pypi
safetensors               0.3.0                    pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                65.6.3          py310h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.40.1               h5082296_0
tk                        8.6.12               h1ccaba5_0
tokenizers                0.13.2                   pypi_0    pypi
torchaudio                0.13.1                py310_cpu    pytorch
torchvision               0.14.1                py310_cpu    pytorch
typing_extensions         4.4.0           py310h06a4308_0
tzdata                    2022g                h04d1e81_0
urllib3                   1.26.14         py310h06a4308_0
wheel                     0.38.4          py310h06a4308_0
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.10               h5eee18b_1
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.2                ha4553b6_0
```

**Comment by mpah** [comment]
same on google colab

**Comment by thulle** [comment]
```
diff --git a/llama.py b/llama.py
index 09b527e..cc652dd 100644
--- a/llama.py
+++ b/llama.py
@@ -238,7 +238,7 @@ def load_quant(model, checkpoint, wbits):
     make_quant(model, layers, wbits)
 
     print('Loading model ...')
-    if checkpoint.endswith('.safetensors'):
+    if checkpoint.as_posix().endswith('.safetensors'):
         from safetensors.torch import load_file as safe_load
         model.load_state_dict(safe_load(checkpoint))
     else:
```

that patch worked for me in linux at least

**Comment by aaronsantiago** [comment]
Same on windows native. A similar solution worked for me (skipping that check entirely).

**Comment by qwopqwop200** [comment]
Fixed a bug.
Please test if you still have such problem.
I didn't encounter such problem with wsl2.

**Comment by TheTerrasque** [comment]
I can confirm the same problem with current code: 

text-generation-webui-text-generation-webui-1  | Loading llama-13b...
text-generation-webui-text-generation-webui-1  | Loading model ...
text-generation-webui-text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-text-generation-webui-1  |   File "/app/server.py", line 194, in <module>
text-generation-webui-text-generation-webui-1  |     shared.model, shared.tokenizer = load_model(shared.model_name)
text-generation-webui-text-generation-webui-1  |   File "/app/modules/models.py", line 119, in load_model
text-generation-webui-text-generation-webui-1  |     model = load_quant(path_to_model, Path(f"models/{pt_model}"), 4)
text-generation-webui-text-generation-webui-1  |   File "/app/repositories/GPTQ-for-LLaMa/llama.py", line 241, in load_quant
text-generation-webui-text-generation-webui-1  |     if checkpoint.endswith('.safetensors'):
text-generation-webui-text-generation-webui-1  | AttributeError: 'PosixPath' object has no attribute 'endswith'

Docker under Windows, python 3.10
