### ISSUE TITLE
converting local hf model with llama.py

### ISSUE THREAD

**Issue by alexl83** [qwopqwop200/GPTQ-for-LLaMa#32]
Hi @qwopqwop200,
I'm trying to convert LLaMA HF models to 4bit, all files being local (input and output)
I get this error about hf token:

`python llama.py /media/alex/Daemon/AI/LLaMA-HF/llama-7b c4 --wbits 4 --save /media/alex/Daemon/AI/LLaMA-HF/llama-7b/llama-7b-4bit.pt
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:03<00:00,  8.45it/s]
Traceback (most recent call last):
  File "/home/alex/oobabooga/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 401, in <module>
    dataloader, testloader = get_loaders(
  File "/home/alex/oobabooga/text-generation-webui/repositories/GPTQ-for-LLaMa/datautils.py", line 111, in get_loaders
    return get_c4(nsamples, seed, seqlen, model)
  File "/home/alex/oobabooga/text-generation-webui/repositories/GPTQ-for-LLaMa/datautils.py", line 56, in get_c4
    traindata = load_dataset(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/datasets/load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/datasets/load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/datasets/load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/datasets/load.py", line 1185, in dataset_module_factory
    raise e
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/datasets/load.py", line 1158, in dataset_module_factory
    dataset_info = hf_api_dataset_info(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/datasets/utils/_hf_hub_fixes.py", line 152, in dataset_info
    return hf_api.dataset_info(repo_id, revision=revision, timeout=timeout, use_auth_token=use_auth_token)
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1676, in dataset_info
    headers = self._build_hf_headers(token=token)
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 4205, in _build_hf_headers
    return build_hf_headers(
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/huggingface_hub/utils/_headers.py", line 117, in build_hf_headers
    token_to_send = get_token_to_send(token)
  File "/home/alex/oobabooga/installer_files/env/lib/python3.10/site-packages/huggingface_hub/utils/_headers.py", line 149, in get_token_to_send
    raise EnvironmentError(
OSError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
`

What am I missing? I'm stuck

Thank you!
Ale

**Comment by alexl83** [comment]
sorry - misfire issue - please ignore it

**Comment by merlinarer** [comment]
> sorry - misfire issue - please ignore it

I met the same error, how to ignore? I mean dataloader is needed then, comment L405 will not solve it.

**Comment by alexl83** [comment]
Hi @merlinaer, you need to:
- creat a HuggingFace account
- generate a token from HuggingFace account webpage (read-only  token is enough)
- login from you computer using "huggingface-cli login" --> it will ask for your generated token, then will login

Conversion will work afterwards
Hope it helps

Ale
