### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 3 and 4

### ISSUE THREAD

**Issue by enn-nafnlaus** [qwopqwop200/GPTQ-for-LLaMa#43]
The following command: 

 _python repositories/GPTQ-for-LLaMa/llama.py /path/to/my/text-generation-webui/models/llama-7b c4 --wbits 4 --save llama-7b-4bit.pt_

Fails with:

__Traceback (most recent call last):
File "/path/to/my/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 410, in
quantizers = llama_sequential(model, dataloader, DEV)
File "/usr/local/lib64/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/path/to/my/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 88, in llama_sequential
outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask)[0]
File "/usr/local/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 318, in forward
hidden_states, self_attn_weights, present_key_value = self.self_attn(
File "/usr/local/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in call_impl
return forward_call(*input, **kwargs)
File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 228, in forward
query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, offset=offset)
File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 142, in apply_rotary_pos_emb
q_embed = (q * cos) + (rotate_half(q) * sin)
File "/my/homedir/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 136, in rotate_half
return torch.cat((-x2, x1), dim=-1)
**RuntimeError: Tensors must have same number of dimensions: got 3 and 4**_

Any thoughts on what might be wrong?  That source model works just fine on its own.

I've tried downloading models converted by others and using them in text-generation-webui. The server starts fine, but whenever I click generate, I again get the same _"Tensors must have same number of dimensions"_ error. 

In case it matters, I do have two GPUs.  But setting CUDA_VISIBLE_DEVICES=0 doesn't help, neither with llama.py nor text-generation-webui's server.py. Nor does --gpu_memory 5 5 or similar help in text-generation-webui.

**Comment by enn-nafnlaus** [comment]
ED: this might be the solution:

pip uninstall transformers 
pip install git+https://github.com/zphang/transformers.git@68d640f7c368bcaaaecfc678f11908ebbd3d6176

**Comment by qwopqwop200** [comment]
You seem to have solved this problem. I will close the issue.

**Comment by musabgultekin** [comment]
This problem still exists, I solved with the same way as @enn-nafnlaus after trying different thins for 1 hour . 

@qwopqwop200 What is the commit hash that you use mainly in https://github.com/zphang/transformers/tree/llama_push ?
Cause he changed lots of things and lots of stuff is broken rn. If you can pin the exact commit in the requirements.txt, that would be way better.

**Comment by qwopqwop200** [comment]
As per your suggestion, we will use a fixed commit version until the Transformer is stable.
