### ISSUE TITLE
AttributeError: 'LLaMAModel' object has no attribute 'decoder'

### ISSUE THREAD

**Issue by a2012456373** [qwopqwop200/GPTQ-for-LLaMa#5]
CUDA_VISIBLE_DEVICES=0 python llama.py decapoda-research/llama-7b-hf c4

Traceback (most recent call last):
  File "llama.py", line 419, in <module>
    llama_eval(model, testloader, DEV)
  File "/home/zhangjp/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "llama.py", line 121, in llama_eval
    layers = model.model.decoder.layers
  File "/home/zhangjp/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LLaMAModel' object has no attribute 'decoder'

**Comment by qwopqwop200** [comment]
Currently, the problem is caused by a code change in the Transformer library.
i will update soon.

**Comment by qwopqwop200** [comment]
fix it
